apiVersion: apps/v1
kind: Deployment
metadata:
  name: airlinesreservationsample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airlinesreservationsample
  template:
    metadata:
      labels:
        app: airlinesreservationsample
    spec:
      containers:
      - name: airlinesreservationsample
        image: <AZ_CONTAINER_REGISTRY>.azurecr.io/airlinesreservationsample:latest
        resources:
          requests:
            cpu: "1"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "2Gi"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: airlinesreservationsample
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: airlinesreservationsample